#!/cds/group/pcds/epics/ioc/common/pvNotepad/R2.1.0/bin/rhel7-x86_64/pvNotepad

epicsEnvSet( "EPICS_NAME", "IOC:LAS:FSTIMING:GLUEPV" )
epicsEnvSet( "ENGINEER",  "Christina Pino (cpino)" )
epicsEnvSet( "LOCATION",  "SLAC:LCLS:LAS" )
epicsEnvSet( "IOCSH_PS1", "ioc-las-fstiming-gluePV> ")
epicsEnvSet( "IOCTOP",       "/cds/group/pcds/epics/ioc/common/pvNotepad/R2.1.0" )
epicsEnvSet( "BUILD_TOP",    "/reg/g/pcds/epics/ioc/las/pvNotepad/R1.0.4/build" )
epicsEnvSet( "EPICS_PVA_AUTO_ADDR_LIST",         "TRUE" )
epicsEnvSet( "EPICS_PVAS_AUTO_BEACON_ADDR_LIST", "TRUE" )

< envPaths

# Run common startup commands for linux soft IOC's
< /reg/d/iocCommon/All/pre_linux.cmd

# Register all support components
dbLoadDatabase("$(TOP)/dbd/pvNotepad.dbd")
pvNotepad_registerRecordDeviceDriver(pdbbase)

# Load record instances
dbLoadRecords("$(TOP)/db/iocSoft.db",            "IOC=$(EPICS_NAME)" )
dbLoadRecords("$(TOP)/db/save_restoreStatus.db", "P=$(EPICS_NAME):" )

#Standard array option

dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:03")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:04")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:05")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:06")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:07")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:08")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:09")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:10")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:11")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:12")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:13")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:14")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:15")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:16")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:17")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:18")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:19")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:20")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:21")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:22")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:23")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:24")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:25")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:26")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:27")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:28")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:29")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:30")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:31")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:32")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:33")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:34")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:35")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:36")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:37")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:38")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:39")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:40")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:41")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:42")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:43")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:44")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:45")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:46")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:47")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:48")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:49")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:50")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:51")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:52")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:53")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:54")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:55")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:56")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:57")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:58")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:59")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:60")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:61")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:62")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:63")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:64")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:65")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:66")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:67")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:68")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:69")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:70")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:71")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:72")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:73")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:74")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:75")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:76")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:77")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:78")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:79")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:80")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:81")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:82")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:83")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:84")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:85")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:86")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:87")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:88")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:89")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:90")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:91")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:92")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:93")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:94")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:95")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:96")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:97")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:98")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:99")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:100")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:101")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:102")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:103")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:104")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:105")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:106")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:107")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:108")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:109")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:100")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:111")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:112")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:113")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:114")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:115")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:116")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:117")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:118")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:119")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDH:FLOAT:120")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:03")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:04")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:05")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:06")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:07")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:08")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:09")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:10")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:11")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:12")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:13")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:14")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:15")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:16")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:17")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:18")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:19")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:20")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:21")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:22")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:23")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:24")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:25")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:26")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:27")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:28")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:29")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:30")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:31")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:32")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:33")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:34")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:35")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:36")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:37")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:38")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:39")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:40")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:41")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:42")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:43")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:44")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:45")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:46")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:47")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:48")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:49")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:50")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:51")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:52")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:53")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:54")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:55")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:56")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:57")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:58")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:59")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:60")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:61")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:62")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:63")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:64")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:65")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:66")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:67")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:68")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:69")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:70")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:71")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:72")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:73")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:74")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:75")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:76")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:77")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:78")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:79")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:80")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:81")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:82")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:83")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:84")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:85")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:86")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:87")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:88")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:89")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:90")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:91")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:92")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:93")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:94")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:95")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:96")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:97")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:98")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:99")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:100")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:101")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:102")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:103")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:104")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:105")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:106")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:107")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:108")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:109")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:110")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:111")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:112")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:113")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=LAS:UNDS:FLOAT:114")

# Setup autosave
save_restoreSet_status_prefix("$(EPICS_NAME):" )
save_restoreSet_IncompleteSetsOk( 1 )
save_restoreSet_DatedBackupFiles( 1 )

set_requestfile_path( "$(PWD)/../../autosave"             )
set_savefile_path   ( "$(IOC_DATA)/ioc-las-fstiming-gluePV/autosave" )

set_pass0_restoreFile( "ioc-las-fstiming-gluePV.sav" )        #just restore the settings
set_pass1_restoreFile( "ioc-las-fstiming-gluePV.sav" )        #just restore the settings


# Initialize the IOC and start processing records
iocInit()

# Start autosave backups
create_monitor_set( "ioc-las-fstiming-gluePV.req", 30, "" )

# All IOCs should dump some common info after initial startup.
< /reg/d/iocCommon/All/post_linux.cmd

