#!/reg/g/pcds/epics/ioc/common/pvNotepad/R2.0.3/bin/linux-x86_64/pvNotepad

epicsEnvSet( "EPICS_NAME", "IOC:XCS:USERPV" )
epicsEnvSet( "ENGINEER",  "Daniel Damiani (ddamiani)" )
epicsEnvSet( "LOCATION",  "SLAC:LCLS:XCS" )
epicsEnvSet( "IOCSH_PS1", "ioc-xcs-userPV> ")

< envPaths

# Run common startup commands for linux soft IOC's
< /reg/d/iocCommon/All/pre_linux.cmd

# Register all support components
dbLoadDatabase("$(TOP)/dbd/pvNotepad.dbd")
pvNotepad_registerRecordDeviceDriver(pdbbase)

# Load record instances
dbLoadRecords("$(TOP)/db/iocSoft.db",            "IOC=$(EPICS_NAME)" )
dbLoadRecords("$(TOP)/db/save_restoreStatus.db", "P=$(EPICS_NAME):" )

#Standard array option

dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:SCAN:NSHOTS")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:SCAN:NSTEPS")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:SCAN:ISTEP")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:SCAN:ISSCAN,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:SCAN:SCANVAR00,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:SCAN:SCANVAR01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:SCAN:SCANVAR02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MIN00")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MIN01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MIN02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MAX00")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MAX01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:SCAN:MAX02")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:01")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:02")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:03")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:04")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:05")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:06")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:07")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:08")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:09")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:INT:10")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:01,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:02,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:03,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:04,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:05,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:06,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:07,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:08,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:09,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XCS:VARS:DIG:10,ZNAM=Off,ONAM=On,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:03,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:04,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:05,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:06,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:07,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:08,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:09,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:STRING:10,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:03")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:04")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:05")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:06")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:07")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:08")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:09")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:FLT:10")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD0:TEMP0,PREC=4,DESC=DET:"QUAD0 Temperature 0",SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD0:TEMP1,PREC=4,DESC=DET:QUAD0 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD0:TEMP2,PREC=4,DESC=DET:QUAD0 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD0:TEMP3,PREC=4,DESC=DET:QUAD0 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD1:TEMP0,PREC=4,DESC=DET:QUAD1 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD1:TEMP1,PREC=4,DESC=DET:QUAD1 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD1:TEMP2,PREC=4,DESC=DET:QUAD1 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD1:TEMP3,PREC=4,DESC=DET:QUAD1 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD2:TEMP0,PREC=4,DESC=DET:QUAD2 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD2:TEMP1,PREC=4,DESC=DET:QUAD2 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD2:TEMP2,PREC=4,DESC=DET:QUAD2 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD2:TEMP3,PREC=4,DESC=DET:QUAD2 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD3:TEMP0,PREC=4,DESC=DET:QUAD3 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD3:TEMP1,PREC=4,DESC=DET:QUAD3 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD3:TEMP2,PREC=4,DESC=DET:QUAD3 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:DET:QUAD3:TEMP3,PREC=4,DESC=DET:QUAD3 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:GON:140K:TEMP0,PREC=4,DESC=GON:140K CsPad Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:GON:140K:TEMP1,PREC=4,DESC=GON:140K CsPad Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:GON:140K:TEMP2,PREC=4,DESC=GON:140K CsPad Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:GON:140K:TEMP3,PREC=4,DESC=GON:140K CsPad Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAM:140K:TEMP0,PREC=4,DESC=LAM:140K CsPad Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAM:140K:TEMP1,PREC=4,DESC=LAM:140K CsPad Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAM:140K:TEMP2,PREC=4,DESC=LAM:140K CsPad Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAM:140K:TEMP3,PREC=4,DESC=LAM:140K CsPad Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:SET1,PREC=16,DESC=MCC Photon Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:SET2,PREC=16,DESC=MCC Photon Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:REF1,PREC=16,DESC=MCC Photon Energy Reference,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:REF2,PREC=16,DESC=MCC Photon Energy Reference,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:VER,PREC=16,DESC=MCC Photon Energy PV Vernier,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:UND,PREC=16,DESC=MCC Photon Energy PV Undulator,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:MCC:EPHOT:REQ,PREC=16,DESC=MCC Photon Energy PV Request,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:LOM:Ref,DESC=Output Reflection of LODCM,DTYP=Soft Channel,PINI=YES")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:DET:x_Motor,DESC=X-Motor detector mover,DTYP=Soft Channel,PINI=YES")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:DET:y_Motor,DESC=Y-Motor detector mover,DTYP=Soft Channel,PINI=YES")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:DET:th_Motor,DESC=Theta-Motor detector mover,DTYP=Soft Channel,PINI=YES")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XCS:VARS:E86:G2_ATT,DESC=G2 attenuator preset state,DTYP=Soft Channel,PINI=YES")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:710:det_roi_x1,DESC=L710 Hill PI ROI x1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:710:det_roi_y1,DESC=L710 Hill PI ROI y1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:710:det_roi_x2,DESC=L710 Hill PI ROI x2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XCS:VARS:710:det_roi_y2,DESC=L710 Hill PI ROI y2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:LOM:E,PREC=6,DESC=Output Energy of LODCM (eV),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:LOM:E1,PREC=6,DESC=Tower 1 Energy of LODCM (eV),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:LOM:E2,PREC=6,DESC=Tower 2 Energy of LODCM (eV),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:CCM:E,PREC=6,DESC=Output Energy of CCM (eV),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:LAM:Theta,PREC=6,DESC=Theta Angle of LADM (deg),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:LAM:Gamma,PREC=6,DESC=Gamma Angle of LADM (deg),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:ATT:T,PREC=6,DESC=Trans of XCS Att at 1st Harm,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:ATT:T3,PREC=6,DESC=Trans of XCS Att at 3rd Harm,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:ATT:E,PREC=6,DESC=Energy for T-calc in XCS Att,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:GON:REF,PREC=6,DESC=Refl of Diff S/D Stages,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:GON:REFD,PREC=6,DESC=Refl of Diff Det Stage,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:MCC:EPHOT_ULIM_LO,PREC=6,DESC=MCC Vernier LowLim,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:MCC:EPHOT_ULIM_HI,PREC=6,DESC=MCC Vernier HiLim,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:MCC:EPHOT,PREC=6,DESC=MCC Vernier Value,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DAQ:PI1_TEMP,PREC=6,DESC=Princeton Det-1 Temp (C),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DAQ:PI_SHOTS,PREC=6,DESC=Princeton Shots per frame,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DAQ:PI_FRAMES,PREC=6,DESC=Princeton Frames per cycle,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:geometry,PREC=6,DESC=Det Geom (0=Trans, 1=Spec),SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:s2d,PREC=6,DESC=Sample-Detector distance,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:x_Pix0,PREC=6,DESC=X-Pixel transmitted beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:y_Pix0,PREC=6,DESC=Y-Pixel transmitted beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:x_Pos0,PREC=6,DESC=X-Pos transmitted beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:y_Pos0,PREC=6,DESC=Y-Pos transmitted beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:th_Pos0,PREC=6,DESC=Theta-Pos transmitted beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:x_PixS,PREC=6,DESC=X-Pixel specular beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:y_PixS,PREC=6,DESC=Y-Pixel specular beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:x_PosS,PREC=6,DESC=X-Pos specular beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:y_PosS,PREC=6,DESC=Y-Pos specular beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:DET:th_PosS,PREC=6,DESC=Theta-Pos specular beam,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:710:Lattice_Const,PREC=6,DESC=L710 Hill Lattice Constant,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:710:Analyzer_Energy,PREC=6,DESC=L710 Hill Lattice Constant,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:710:ea_lowlim,PREC=6,DESC=L710 Hill Analyzer E Lowlim,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:710:ea_highlim,PREC=6,DESC=L710 Hill Analyzer E Highlim,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT_T,PREC=6,DESC=LE86 Trasmission of G2 ATT,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATTALL_T,PREC=6,DESC=LE86 Transmit of G2 attall,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT0_T,PREC=6,DESC=LE86 Transmit of G2 att0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT10_T,PREC=6,DESC=LE86 Transmit of G2 att10,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT20_T,PREC=6,DESC=LE86 Transmit of G2 att20,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT30_T,PREC=6,DESC=LE86 Transmit of G2 att30,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT40_T,PREC=6,DESC=LE86 Transmit of G2 att40,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT50_T,PREC=6,DESC=LE86 Transmit of G2 att50,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT60_T,PREC=6,DESC=LE86 Transmit of G2 att60,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT70_T,PREC=6,DESC=LE86 Transmit of G2 att70,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT80_T,PREC=6,DESC=LE86 Transmit of G2 att80,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT90_T,PREC=6,DESC=LE86 Transmit of G2 att90,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT120_T,PREC=6,DESC=LE86 Transmit of G2 att120,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT130_T,PREC=6,DESC=LE86 Transmit of G2 att130,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT140_T,PREC=6,DESC=LE86 Transmit of G2 att140,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT150_T,PREC=6,DESC=LE86 Transmit of G2 att150,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT160_T,PREC=6,DESC=LE86 Transmit of G2 att160,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT170_T,PREC=6,DESC=LE86 Transmit of G2 att170,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT180_T,PREC=6,DESC=LE86 Transmit of G2 att180,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT190_T,PREC=6,DESC=LE86 Transmit of G2 att190,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT200_T,PREC=6,DESC=LE86 Transmit of G2 att200,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATTALL_X,PREC=6,DESC=LE86 Motor X of G2 attall,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT0_X,PREC=6,DESC=LE86 Motor X of G2 att0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT10_X,PREC=6,DESC=LE86 Motor X of G2 att10,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT20_X,PREC=6,DESC=LE86 Motor X of G2 att20,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT30_X,PREC=6,DESC=LE86 Motor X of G2 att30,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT40_X,PREC=6,DESC=LE86 Motor X of G2 att40,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT50_X,PREC=6,DESC=LE86 Motor X of G2 att50,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT60_X,PREC=6,DESC=LE86 Motor X of G2 att60,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT70_X,PREC=6,DESC=LE86 Motor X of G2 att70,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT80_X,PREC=6,DESC=LE86 Motor X of G2 att80,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT90_X,PREC=6,DESC=LE86 Motor X of G2 att90,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT120_X,PREC=6,DESC=LE86 Motor X of G2 att120,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT130_X,PREC=6,DESC=LE86 Motor X of G2 att130,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT140_X,PREC=6,DESC=LE86 Motor X of G2 att140,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT150_X,PREC=6,DESC=LE86 Motor X of G2 att150,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT160_X,PREC=6,DESC=LE86 Motor X of G2 att160,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT170_X,PREC=6,DESC=LE86 Motor X of G2 att170,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT180_X,PREC=6,DESC=LE86 Motor X of G2 att180,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT190_X,PREC=6,DESC=LE86 Motor X of G2 att190,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT200_X,PREC=6,DESC=LE86 Motor X of G2 att200,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATTALL_Y,PREC=6,DESC=LE86 Motor Y of G2 attall,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT0_Y,PREC=6,DESC=LE86 Motor Y of G2 att0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT10_Y,PREC=6,DESC=LE86 Motor Y of G2 att10,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT20_Y,PREC=6,DESC=LE86 Motor Y of G2 att20,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT30_Y,PREC=6,DESC=LE86 Motor Y of G2 att30,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT40_Y,PREC=6,DESC=LE86 Motor Y of G2 att40,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT50_Y,PREC=6,DESC=LE86 Motor Y of G2 att50,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT60_Y,PREC=6,DESC=LE86 Motor Y of G2 att60,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT70_Y,PREC=6,DESC=LE86 Motor Y of G2 att70,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT80_Y,PREC=6,DESC=LE86 Motor Y of G2 att80,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT90_Y,PREC=6,DESC=LE86 Motor Y of G2 att90,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT120_Y,PREC=6,DESC=LE86 Motor Y of G2 att120,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT130_Y,PREC=6,DESC=LE86 Motor Y of G2 att130,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT140_Y,PREC=6,DESC=LE86 Motor Y of G2 att140,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT150_Y,PREC=6,DESC=LE86 Motor Y of G2 att150,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT160_Y,PREC=6,DESC=LE86 Motor Y of G2 att160,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT170_Y,PREC=6,DESC=LE86 Motor Y of G2 att170,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT180_Y,PREC=6,DESC=LE86 Motor Y of G2 att180,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT190_Y,PREC=6,DESC=LE86 Motor Y of G2 att190,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:E86:G2_ATT200_Y,PREC=6,DESC=LE86 Motor Y of G2 att200,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:VARS:J78:GDET_THRES,PREC=6,DESC=LJ78 Gas Detector Threshold,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:CCM:E,PREC=16,DESC=CCM Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:CCM:Theta0,PREC=16,DESC=CCM Theta0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:FS4:T0_SHIFTER,PREC=16,DESC=XCS Laser FS4 T0_SHIFTER,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:T0_MONITOR,PREC=16,DESC=XCS Laser T0_MONITOR,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E_PULSE,PREC=16,DESC=XCS Laser E_PULSE,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E0,PREC=16,DESC=XCS Laser E0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E_LEAK,PREC=16,DESC=XCS Laser E_LEAK,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TIME_DELAY,PREC=16,DESC=XCS Laser Time Delay,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:FS4_MIN,PREC=16,DESC=XCS Laser FS4 Min,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:FS4_MAX,PREC=16,DESC=XCS Laser FS4 MAX,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:EVR0_OSC,PREC=16,DESC=XCS Laser EVR0_Osc.,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:EVR0_GATE,PREC=16,DESC=XCS Laser EVR0 Gate,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:SDG0,PREC=16,DESC=XCS Laser SDG0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E_PULSE2,PREC=16,DESC=XCS Laser 2 E_Pulse,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E02,PREC=16,DESC=XCS Laser 2 E0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:E_LEAK2,PREC=16,DESC=XCS Laser 2 E_LEAK,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:VIT:T0,PREC=16,DESC=XCS Laser Vitara T0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:VIT:TD,PREC=16,DESC=XCS Laser Vitara TD,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LXT,PREC=16,DESC=XCS LXT,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LXTTC,PREC=16,DESC=XCS LXTTC,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:CP_WP_POS,PREC=16,DESC=XCS Laser CP Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:CP_WP_OFF,PREC=16,DESC=XCS Laser CP Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OUT_WP_POS,PREC=16,DESC=XCS Laser OUT Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OUT_WP_OFF,PREC=16,DESC=XCS Laser OUT Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:CP_TRA_POS,PREC=16,DESC=XCS Laser CP Trans Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:CP_TRA_OFF,PREC=16,DESC=XCS Laser CP Trans OFF,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_H_POS,PREC=16,DESC=XCS Laser L1 Horizontal Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_H_OFF,PREC=16,DESC=XCS Laser L1 Horizontal Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_V_POS,PREC=16,DESC=XCS Laser L1 Vertical Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_V_OFF,PREC=16,DESC=XCS Laser L1 Vertical Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_F_POS,PREC=16,DESC=XCS Laser L1 Focus Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:L1_F_OFF,PREC=16,DESC=XCS Laser L1 Focus Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OPA_WP_POS,PREC=16,DESC=XCS Laser OPA Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OPA_WP_OFF,PREC=16,DESC=XCS Laser OPA Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OPA_COMP_POS,PREC=16,DESC=XCS Laser OPA Compressor Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:OPA_COMP_OFF,PREC=16,DESC=XCS Laser OPA Compressor Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_WP_POS,PREC=16,DESC=XCS Laser TT Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_WP_OFF,PREC=16,DESC=XCS Laser TT Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_COMP_POS,PREC=16,DESC=XCS Laser TT Compressor Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_COMP_OFF,PREC=16,DESC=XCS Laser TT Compressor Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSH_POS,PREC=16,DESC=XCS Laser TT Lens Horiz. Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSH_OFF,PREC=16,DESC=XCS Laser TT Lens Horiz. Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSV_POS,PREC=16,DESC=XCS Laser TT Lens Vert. Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSV_OFF,PREC=16,DESC=XCS Laser TT Lens Vert. Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSF_POS,PREC=16,DESC=XCS Laser TT Lens Focus Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_LENSF_OFF,PREC=16,DESC=XCS Laser TT Lens Focus Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_DELAY_POS,PREC=16,DESC=XCS Laser tt_delay Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:USER:LAS:TT_DELAY_OFF,PREC=16,DESC=XCS Laser tt_delay Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XCS:TIMETOOL:TTALL,NELM=6,NORD=3,FTYPE=DOUBLE,EGU=Counts,PREC=16,DESC=XCS TT PeakPos Ampl Vector,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:CCM:THETA0,PREC=16,DESC=CCM Calc theta0 constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:CCM:DSPACING,PREC=16,DESC=CCM Calc dspacing constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:CCM:GR,PREC=16,DESC=CCM Calc gr constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XCS:CCM:GD,PREC=16,DESC=CCM Calc gd constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")

# Setup autosave
save_restoreSet_status_prefix("$(EPICS_NAME):" )
save_restoreSet_IncompleteSetsOk( 1 )
save_restoreSet_DatedBackupFiles( 1 )

set_requestfile_path( "$(PWD)/../../autosave"             )
set_savefile_path   ( "$(IOC_DATA)/ioc-xcs-userPV/autosave" )

set_pass0_restoreFile( "ioc-xcs-userPV.sav" )        #just restore the settings
set_pass1_restoreFile( "ioc-xcs-userPV.sav" )        #just restore the settings


# Initialize the IOC and start processing records
iocInit()

# Start autosave backups
create_monitor_set( "ioc-xcs-userPV.req", 30, "" )

# All IOCs should dump some common info after initial startup.
< /reg/d/iocCommon/All/post_linux.cmd

