#!/reg/g/pcds/epics/ioc/common/timetool/R1.0.7/bin/rhel7-x86_64/gsd

epicsEnvSet( "IOCNAME",	  "ioc-ued-rf" )
epicsEnvSet( "ENGINEER",  "Michael Browne (mcbrowne)" )
epicsEnvSet( "LOCATION",  "Somewhere" )
epicsEnvSet( "IOCSH_PS1", "$(IOCNAME)> " )
epicsEnvSet( "IOC_PV",	  "IOC:UED:RF:01" )
epicsEnvSet("EVRID_PMC",  "1")
epicsEnvSet("EVRID_SLAC", "15")
epicsEnvSet("EVRDB_PMC",  "db/evrPmc230.db")
epicsEnvSet("EVRDB_SLAC", "db/evrSLAC.db")
epicsEnvSet( "IOCTOP",	  "/reg/g/pcds/epics/ioc/common/timetool/R1.0.7" )
< envPaths
epicsEnvSet("TOP", "/reg/g/pcds/epics/ioc/common/timetool/R1.0.7/children/build")
cd("$(IOCTOP)")

# Run common startup commands for linux soft IOC's
< /reg/d/iocCommon/All/pre_linux.cmd

epicsEnvSet("EPICS_CA_AUTO_ADDR_LIST", "NO")
epicsEnvSet("EPICS_CA_ADDR_LIST", "172.21.36.255:5064 172.27.99.255:5058")

## Register all support components
dbLoadDatabase( "dbd/gsd.dbd" )
gsd_registerRecordDeviceDriver(pdbbase)

ErDebugLevel( 0 )


## Load record instances
dbLoadRecords( "db/iocSoft.db", "IOC=$(IOC_PV)")
dbLoadRecords( "db/save_restoreStatus.db", "P=$(IOC_PV):")


dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT00,REMOTE=SIOC:AS01:KY01:0:AACT_TS00,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT00:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT00,REMOTE=SIOC:AS01:KY01:0:PACT_TS00,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT00:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT01,REMOTE=SIOC:AS01:KY01:0:AACT_TS01,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT01:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT01,REMOTE=SIOC:AS01:KY01:0:PACT_TS01,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT01:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT02,REMOTE=SIOC:AS01:KY01:0:AACT_TS02,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT02:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT02,REMOTE=SIOC:AS01:KY01:0:PACT_TS02,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT02:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT03,REMOTE=SIOC:AS01:KY01:0:AACT_TS03,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT03:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT03,REMOTE=SIOC:AS01:KY01:0:PACT_TS03,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT03:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT04,REMOTE=SIOC:AS01:KY01:0:AACT_TS04,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT04:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT04,REMOTE=SIOC:AS01:KY01:0:PACT_TS04,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT04:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT05,REMOTE=SIOC:AS01:KY01:0:AACT_TS05,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT05:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT05,REMOTE=SIOC:AS01:KY01:0:PACT_TS05,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT05:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT06,REMOTE=SIOC:AS01:KY01:0:AACT_TS06,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT06:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT06,REMOTE=SIOC:AS01:KY01:0:PACT_TS06,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT06:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT07,REMOTE=SIOC:AS01:KY01:0:AACT_TS07,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT07:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT07,REMOTE=SIOC:AS01:KY01:0:PACT_TS07,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT07:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT08,REMOTE=SIOC:AS01:KY01:0:AACT_TS08,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT08:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT08,REMOTE=SIOC:AS01:KY01:0:PACT_TS08,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT08:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT09,REMOTE=SIOC:AS01:KY01:0:AACT_TS09,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT09:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT09,REMOTE=SIOC:AS01:KY01:0:PACT_TS09,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT09:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT10,REMOTE=SIOC:AS01:KY01:0:AACT_TS10,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT10:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT10,REMOTE=SIOC:AS01:KY01:0:PACT_TS10,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT10:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT11,REMOTE=SIOC:AS01:KY01:0:AACT_TS11,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT11:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT11,REMOTE=SIOC:AS01:KY01:0:PACT_TS11,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT11:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT12,REMOTE=SIOC:AS01:KY01:0:AACT_TS12,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT12:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT12,REMOTE=SIOC:AS01:KY01:0:PACT_TS12,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT12:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT13,REMOTE=SIOC:AS01:KY01:0:AACT_TS13,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT13:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT13,REMOTE=SIOC:AS01:KY01:0:PACT_TS13,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT13:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT14,REMOTE=SIOC:AS01:KY01:0:AACT_TS14,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT14:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT14,REMOTE=SIOC:AS01:KY01:0:PACT_TS14,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT14:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT15,REMOTE=SIOC:AS01:KY01:0:AACT_TS15,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT15:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT15,REMOTE=SIOC:AS01:KY01:0:PACT_TS15,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT15:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT16,REMOTE=SIOC:AS01:KY01:0:AACT_TS16,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT16:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT16,REMOTE=SIOC:AS01:KY01:0:PACT_TS16,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT16:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=AACT17,REMOTE=SIOC:AS01:KY01:0:AACT_TS17,FLNK=UED:RF:01:AACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:AACT17:DESC,FLNK=UED:RF:01:AACTBUILD:MAKE_DESC" )
dbLoadRecords( "db/local.db", "BASE=UED:RF:01,NAME=PACT17,REMOTE=SIOC:AS01:KY01:0:PACT_TS17,FLNK=UED:RF:01:PACTBUILD" )
dbLoadRecords( "db/flnk.db", "NAME=UED:RF:01:PACT17:DESC,FLNK=UED:RF:01:PACTBUILD:MAKE_DESC" )

dbLoadRecords( "db/output.db", "BASE=UED:RF:01,NAME=AACT,TSEL=UED:RF:01:AACTBUILD.TIME" )
dbLoadRecords( "db/output.db", "BASE=UED:RF:01,NAME=AACT_IDX,TSEL=UED:RF:01:AACTBUILD.TIME,TYPE=longout" )
dbLoadRecords( "db/output.db", "BASE=UED:RF:01,NAME=PACT,TSEL=UED:RF:01:PACTBUILD.TIME" )
dbLoadRecords( "db/output.db", "BASE=UED:RF:01,NAME=PACT_IDX,TSEL=UED:RF:01:PACTBUILD.TIME,TYPE=longout" )


dbLoadRecords( "db/lbuild.db", "NAME=UED:RF:01:AACTBUILD,INPA=UED:RF:01:AACT00,INPB=UED:RF:01:AACT01,INPC=UED:RF:01:AACT02,INPD=UED:RF:01:AACT03,INPE=UED:RF:01:AACT04,INPF=UED:RF:01:AACT05,INPG=UED:RF:01:AACT06,INPH=UED:RF:01:AACT07,INPI=UED:RF:01:AACT08,INPJ=UED:RF:01:AACT09,INPK=UED:RF:01:AACT10,INPL=UED:RF:01:AACT11,INPM=UED:RF:01:AACT12,INPN=UED:RF:01:AACT13,INPO=UED:RF:01:AACT14,INPP=UED:RF:01:AACT15,INPQ=UED:RF:01:AACT16,INPR=UED:RF:01:AACT17,OUT=UED:RF:01:AACT PP NMS,INDEX=UED:RF:01:AACT_IDX PP NMS" )
dbLoadRecords( "db/lbuild.db", "NAME=UED:RF:01:PACTBUILD,INPA=UED:RF:01:PACT00,INPB=UED:RF:01:PACT01,INPC=UED:RF:01:PACT02,INPD=UED:RF:01:PACT03,INPE=UED:RF:01:PACT04,INPF=UED:RF:01:PACT05,INPG=UED:RF:01:PACT06,INPH=UED:RF:01:PACT07,INPI=UED:RF:01:PACT08,INPJ=UED:RF:01:PACT09,INPK=UED:RF:01:PACT10,INPL=UED:RF:01:PACT11,INPM=UED:RF:01:PACT12,INPN=UED:RF:01:PACT13,INPO=UED:RF:01:PACT14,INPP=UED:RF:01:PACT15,INPQ=UED:RF:01:PACT16,INPR=UED:RF:01:PACT17,OUT=UED:RF:01:PACT PP NMS,INDEX=UED:RF:01:PACT_IDX PP NMS" )

## Setup autosave
set_savefile_path( "$(IOC_DATA)/$(IOC)/autosave" )
set_requestfile_path( "$(TOP)/autosave" )
# Also look in the iocData autosave folder for auto generated req files
set_requestfile_path( "$(IOC_DATA)/$(IOC)/autosave" )
save_restoreSet_status_prefix( "$(IOC_PV):" )
save_restoreSet_IncompleteSetsOk( 1 )
save_restoreSet_DatedBackupFiles( 1 )

set_pass0_restoreFile( "autoSettings.sav" )
set_pass0_restoreFile( "ioc-ued-rf.sav" )

# Initialize the IOC and start processing records
iocInit()

# Create autosave files from info directives
makeAutosaveFileFromDbInfo( "$(IOC_DATA)/$(IOC)/autosave/autoSettings.req", "autosaveFields" )

# Start autosave backups
create_monitor_set( "autoSettings.req", 5, "" )
create_monitor_set( "ioc-ued-rf.req", 5, "" )

# All IOCs should dump some common info after initial startup.
< /reg/d/iocCommon/All/post_linux.cmd

# Initialize the waveform strings.

dbpf UED:RF:01:AACT00:DESC "SIOC:AS01:KY01:0:AACT_TS00"
dbpf UED:RF:01:PACT00:DESC "SIOC:AS01:KY01:0:PACT_TS00"
dbpf UED:RF:01:AACT01:DESC "SIOC:AS01:KY01:0:AACT_TS01"
dbpf UED:RF:01:PACT01:DESC "SIOC:AS01:KY01:0:PACT_TS01"
dbpf UED:RF:01:AACT02:DESC "SIOC:AS01:KY01:0:AACT_TS02"
dbpf UED:RF:01:PACT02:DESC "SIOC:AS01:KY01:0:PACT_TS02"
dbpf UED:RF:01:AACT03:DESC "SIOC:AS01:KY01:0:AACT_TS03"
dbpf UED:RF:01:PACT03:DESC "SIOC:AS01:KY01:0:PACT_TS03"
dbpf UED:RF:01:AACT04:DESC "SIOC:AS01:KY01:0:AACT_TS04"
dbpf UED:RF:01:PACT04:DESC "SIOC:AS01:KY01:0:PACT_TS04"
dbpf UED:RF:01:AACT05:DESC "SIOC:AS01:KY01:0:AACT_TS05"
dbpf UED:RF:01:PACT05:DESC "SIOC:AS01:KY01:0:PACT_TS05"
dbpf UED:RF:01:AACT06:DESC "SIOC:AS01:KY01:0:AACT_TS06"
dbpf UED:RF:01:PACT06:DESC "SIOC:AS01:KY01:0:PACT_TS06"
dbpf UED:RF:01:AACT07:DESC "SIOC:AS01:KY01:0:AACT_TS07"
dbpf UED:RF:01:PACT07:DESC "SIOC:AS01:KY01:0:PACT_TS07"
dbpf UED:RF:01:AACT08:DESC "SIOC:AS01:KY01:0:AACT_TS08"
dbpf UED:RF:01:PACT08:DESC "SIOC:AS01:KY01:0:PACT_TS08"
dbpf UED:RF:01:AACT09:DESC "SIOC:AS01:KY01:0:AACT_TS09"
dbpf UED:RF:01:PACT09:DESC "SIOC:AS01:KY01:0:PACT_TS09"
dbpf UED:RF:01:AACT10:DESC "SIOC:AS01:KY01:0:AACT_TS10"
dbpf UED:RF:01:PACT10:DESC "SIOC:AS01:KY01:0:PACT_TS10"
dbpf UED:RF:01:AACT11:DESC "SIOC:AS01:KY01:0:AACT_TS11"
dbpf UED:RF:01:PACT11:DESC "SIOC:AS01:KY01:0:PACT_TS11"
dbpf UED:RF:01:AACT12:DESC "SIOC:AS01:KY01:0:AACT_TS12"
dbpf UED:RF:01:PACT12:DESC "SIOC:AS01:KY01:0:PACT_TS12"
dbpf UED:RF:01:AACT13:DESC "SIOC:AS01:KY01:0:AACT_TS13"
dbpf UED:RF:01:PACT13:DESC "SIOC:AS01:KY01:0:PACT_TS13"
dbpf UED:RF:01:AACT14:DESC "SIOC:AS01:KY01:0:AACT_TS14"
dbpf UED:RF:01:PACT14:DESC "SIOC:AS01:KY01:0:PACT_TS14"
dbpf UED:RF:01:AACT15:DESC "SIOC:AS01:KY01:0:AACT_TS15"
dbpf UED:RF:01:PACT15:DESC "SIOC:AS01:KY01:0:PACT_TS15"
dbpf UED:RF:01:AACT16:DESC "SIOC:AS01:KY01:0:AACT_TS16"
dbpf UED:RF:01:PACT16:DESC "SIOC:AS01:KY01:0:PACT_TS16"
dbpf UED:RF:01:AACT17:DESC "SIOC:AS01:KY01:0:AACT_TS17"
dbpf UED:RF:01:PACT17:DESC "SIOC:AS01:KY01:0:PACT_TS17"

dbpf UED:RF:01:AACT:DESC "Amplitude"
dbpf UED:RF:01:AACT.DESC "Amplitude"
dbpf UED:RF:01:AACT_IDX:DESC "Amplitude Index"
dbpf UED:RF:01:AACT_IDX.DESC "Amplitude Index"
dbpf UED:RF:01:PACT:DESC "Phase"
dbpf UED:RF:01:PACT.DESC "Phase"
dbpf UED:RF:01:PACT_IDX:DESC "Phase Index"
dbpf UED:RF:01:PACT_IDX.DESC "Phase Index"




