#!/reg/g/pcds/epics/ioc/common/ims/R6.0.0/bin/linux-x86/ims

< envPaths

epicsEnvSet( "EPICS_NAME",           "IOC:MEC:PCI:IMS" )
epicsEnvSet( "LOCATION",             "MEC"  )
epicsEnvSet( "IOCSH_PS1",            "ioc-mec-pci-ims> " )

epicsEnvSet( "DVER",                 "4"           )
epicsEnvSet( "STREAM_PROTOCOL_PATH", "$(IMS)/misc" )

epicsEnvSet( "ENGINEER",             "Evan Rodriguez (erod)"  )


# Run common startup commands for linux soft IOC's
< /reg/d/iocCommon/All/pre_linux.cmd

# Register all support components
dbLoadDatabase( "$(TOP)/dbd/ims.dbd" )
ims_registerRecordDeviceDriver( pdbbase )

# Load record instances
dbLoadRecords( "$(TOP)/db/iocSoft.db",            "IOC=$(EPICS_NAME)" )
dbLoadRecords( "$(TOP)/db/save_restoreStatus.db", "IOC=$(EPICS_NAME)" )
dbLoadRecords( "$(TOP)/db/check_update.db",       "IOC=$(EPICS_NAME)" )










dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:ED:X,PORT=digi-mec-pci02:2104,ASYN=MEC:PCI:MMS:ED:X,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:ED:X,STATE=IN,SET=0,DELTA=0.5,MOVER=MEC:PCI:MMS:ED:X.VAL,RBV=MEC:PCI:MMS:ED:X.RBV,DMOV=MEC:PCI:MMS:ED:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:ED:X,STATE=OUT,SET=50,DELTA=5.0,MOVER=MEC:PCI:MMS:ED:X.VAL,RBV=MEC:PCI:MMS:ED:X.RBV,DMOV=MEC:PCI:MMS:ED:X.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_2states.db", "DEVICE=MEC:PCI:ED:X,STATE1=IN,SEVR1=MINOR,STATE2=OUT,SEVR2=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:ED:X,ALIAS=MEC:PCI:ED:X:MOTOR" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:ED:Y,PORT=digi-mec-pci02:2105,ASYN=MEC:PCI:MMS:ED:Y,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:ED:Y,STATE=IN,SET=0,DELTA=0.5,MOVER=MEC:PCI:MMS:ED:Y.VAL,RBV=MEC:PCI:MMS:ED:Y.RBV,DMOV=MEC:PCI:MMS:ED:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:ED:Y,STATE=OUT,SET=50,DELTA=5.0,MOVER=MEC:PCI:MMS:ED:Y.VAL,RBV=MEC:PCI:MMS:ED:Y.RBV,DMOV=MEC:PCI:MMS:ED:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_2states.db", "DEVICE=MEC:PCI:ED:Y,STATE1=IN,SEVR1=MINOR,STATE2=OUT,SEVR2=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:ED:Y,ALIAS=MEC:PCI:ED:Y:MOTOR" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:PH:Y,PORT=digi-mec-pci01:2102,ASYN=MEC:PCI:MMS:PH:Y,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:PH:Y,STATE=IN,SET=0,DELTA=0.5,MOVER=MEC:PCI:MMS:PH:Y.VAL,RBV=MEC:PCI:MMS:PH:Y.RBV,DMOV=MEC:PCI:MMS:PH:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:PH:Y,STATE=OUT,SET=50,DELTA=5.0,MOVER=MEC:PCI:MMS:PH:Y.VAL,RBV=MEC:PCI:MMS:PH:Y.RBV,DMOV=MEC:PCI:MMS:PH:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_2states.db", "DEVICE=MEC:PCI:PH:Y,STATE1=IN,SEVR1=MINOR,STATE2=OUT,SEVR2=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:PH:Y,ALIAS=MEC:PCI:PH:Y:MOTOR" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:BS:X,PORT=digi-mec-pci01:2104,ASYN=MEC:PCI:MMS:BS:X,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BS:X,STATE=IN,SET=0,DELTA=0.5,MOVER=MEC:PCI:MMS:BS:X.VAL,RBV=MEC:PCI:MMS:BS:X.RBV,DMOV=MEC:PCI:MMS:BS:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BS:X,STATE=OUT,SET=50,DELTA=5.0,MOVER=MEC:PCI:MMS:BS:X.VAL,RBV=MEC:PCI:MMS:BS:X.RBV,DMOV=MEC:PCI:MMS:BS:X.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_2states.db", "DEVICE=MEC:PCI:BS:X,STATE1=IN,SEVR1=MINOR,STATE2=OUT,SEVR2=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:BS:X,ALIAS=MEC:PCI:BS:X:MOTOR" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:BS:Y,PORT=digi-mec-pci01:2105,ASYN=MEC:PCI:MMS:BS:Y,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BS:Y,STATE=IN,SET=0,DELTA=0.5,MOVER=MEC:PCI:MMS:BS:Y.VAL,RBV=MEC:PCI:MMS:BS:Y.RBV,DMOV=MEC:PCI:MMS:BS:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BS:Y,STATE=OUT,SET=50,DELTA=5.0,MOVER=MEC:PCI:MMS:BS:Y.VAL,RBV=MEC:PCI:MMS:BS:Y.RBV,DMOV=MEC:PCI:MMS:BS:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_2states.db", "DEVICE=MEC:PCI:BS:Y,STATE1=IN,SEVR1=MINOR,STATE2=OUT,SEVR2=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:BS:Y,ALIAS=MEC:PCI:BS:Y:MOTOR" )

dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:PH:X,PORT=digi-mec-pci01:2101,ASYN=MEC:PCI:MMS:PH:X,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:PH:Z,PORT=digi-mec-pci01:2103,ASYN=MEC:PCI:MMS:PH:Z,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:BS:Z,PORT=digi-mec-pci01:2106,ASYN=MEC:PCI:MMS:BS:Z,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:TC:X,PORT=digi-mec-pci01:2107,ASYN=MEC:PCI:MMS:TC:X,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:TC:Z,PORT=digi-mec-pci01:2108,ASYN=MEC:PCI:MMS:TC:Z,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:TG:S,PORT=digi-mec-pci02:2101,ASYN=MEC:PCI:MMS:TG:S,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:BL:XC,PORT=digi-mec-pci02:2102,ASYN=MEC:PCI:MMS:BL:XC,DVER=$(DVER),ERBL=" )
dbLoadRecords( "$(TOP)/db/ims_short.db", "IOC=$(EPICS_NAME),MOTOR=MEC:PCI:MMS:BL:ZC,PORT=digi-mec-pci02:2103,ASYN=MEC:PCI:MMS:BL:ZC,DVER=$(DVER),ERBL=" )

dbLoadRecords( "$(TOP)/db/lkup.db", "NAME=MEC:PCI:PH:X,IN=MEC:PCI:MMS:PH:X.RBV CPP,OUT=MEC:PCI:MMS:PH:X.VAL CPP,NMAX=5" )
dbLoadRecords( "$(TOP)/db/lkup.db", "NAME=MEC:PCI:PCI:SLOT,IN=MEC:PCI:MMS:TG:S.RBV CPP,OUT=MEC:PCI:MMS:TG:S.VAL CPP,NMAX=14" )
dbLoadRecords( "$(TOP)/db/lkup.db", "NAME=MEC:PCI:PCI:Y,IN=MEC:PCI:HEX:TG:Ypr:rbv CPP,OUT=MEC:PCI:HEX:TG:Ypr CPP,NMAX=8" )
dbLoadRecords( "$(TOP)/db/lkup.db", "NAME=MEC:PCI:PTY:X,IN=MEC:PCI:MMS:TC:X.RBV CPP,OUT=MEC:PCI:MMS:TC:X.VAL CPP,NMAX=32" )
dbLoadRecords( "$(TOP)/db/lkup.db", "NAME=MEC:PCI:PTY:Y,IN=MEC:PCI:HEX:TG:Ypr:rbv CPP,OUT=MEC:PCI:HEX:TG:Ypr CPP,NMAX=16" )

dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XC,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:XC.VAL,RBV=MEC:PCI:MMS:BL:XC.RBV,DMOV=MEC:PCI:MMS:BL:XC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XC,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:XC.VAL,RBV=MEC:PCI:MMS:BL:XC.RBV,DMOV=MEC:PCI:MMS:BL:XC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XC,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:XC.VAL,RBV=MEC:PCI:MMS:BL:XC.RBV,DMOV=MEC:PCI:MMS:BL:XC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XC,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:XC.VAL,RBV=MEC:PCI:MMS:BL:XC.RBV,DMOV=MEC:PCI:MMS:BL:XC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XC,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:XC.VAL,RBV=MEC:PCI:MMS:BL:XC.RBV,DMOV=MEC:PCI:MMS:BL:XC.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:XC,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:BL:XC,ALIAS=MEC:PCI:BL:XC:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZC,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:ZC.VAL,RBV=MEC:PCI:MMS:BL:ZC.RBV,DMOV=MEC:PCI:MMS:BL:ZC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZC,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:ZC.VAL,RBV=MEC:PCI:MMS:BL:ZC.RBV,DMOV=MEC:PCI:MMS:BL:ZC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZC,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:ZC.VAL,RBV=MEC:PCI:MMS:BL:ZC.RBV,DMOV=MEC:PCI:MMS:BL:ZC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZC,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:ZC.VAL,RBV=MEC:PCI:MMS:BL:ZC.RBV,DMOV=MEC:PCI:MMS:BL:ZC.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZC,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:BL:ZC.VAL,RBV=MEC:PCI:MMS:BL:ZC.RBV,DMOV=MEC:PCI:MMS:BL:ZC.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:ZC,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:BL:ZC,ALIAS=MEC:PCI:BL:ZC:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XF,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:X.VAL,RBV=MEC:PCI:HEX:BL:Xpr:rbv,DMOV=MEC:PCI:HEX:BL:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XF,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:X.VAL,RBV=MEC:PCI:HEX:BL:Xpr:rbv,DMOV=MEC:PCI:HEX:BL:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XF,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:X.VAL,RBV=MEC:PCI:HEX:BL:Xpr:rbv,DMOV=MEC:PCI:HEX:BL:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XF,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:X.VAL,RBV=MEC:PCI:HEX:BL:Xpr:rbv,DMOV=MEC:PCI:HEX:BL:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:XF,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:X.VAL,RBV=MEC:PCI:HEX:BL:Xpr:rbv,DMOV=MEC:PCI:HEX:BL:X.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:XF,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:X,ALIAS=MEC:PCI:BL:XF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:YF,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Y.VAL,RBV=MEC:PCI:HEX:BL:Ypr:rbv,DMOV=MEC:PCI:HEX:BL:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:YF,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Y.VAL,RBV=MEC:PCI:HEX:BL:Ypr:rbv,DMOV=MEC:PCI:HEX:BL:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:YF,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Y.VAL,RBV=MEC:PCI:HEX:BL:Ypr:rbv,DMOV=MEC:PCI:HEX:BL:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:YF,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Y.VAL,RBV=MEC:PCI:HEX:BL:Ypr:rbv,DMOV=MEC:PCI:HEX:BL:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:YF,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Y.VAL,RBV=MEC:PCI:HEX:BL:Ypr:rbv,DMOV=MEC:PCI:HEX:BL:Y.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:YF,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:Y,ALIAS=MEC:PCI:BL:YF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZF,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Z.VAL,RBV=MEC:PCI:HEX:BL:Zpr:rbv,DMOV=MEC:PCI:HEX:BL:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZF,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Z.VAL,RBV=MEC:PCI:HEX:BL:Zpr:rbv,DMOV=MEC:PCI:HEX:BL:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZF,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Z.VAL,RBV=MEC:PCI:HEX:BL:Zpr:rbv,DMOV=MEC:PCI:HEX:BL:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZF,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Z.VAL,RBV=MEC:PCI:HEX:BL:Zpr:rbv,DMOV=MEC:PCI:HEX:BL:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:ZF,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:Z.VAL,RBV=MEC:PCI:HEX:BL:Zpr:rbv,DMOV=MEC:PCI:HEX:BL:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:ZF,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:Z,ALIAS=MEC:PCI:BL:ZF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:U,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:U.VAL,RBV=MEC:PCI:HEX:BL:Upr:rbv,DMOV=MEC:PCI:HEX:BL:U.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:U,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:U.VAL,RBV=MEC:PCI:HEX:BL:Upr:rbv,DMOV=MEC:PCI:HEX:BL:U.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:U,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:U.VAL,RBV=MEC:PCI:HEX:BL:Upr:rbv,DMOV=MEC:PCI:HEX:BL:U.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:U,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:U.VAL,RBV=MEC:PCI:HEX:BL:Upr:rbv,DMOV=MEC:PCI:HEX:BL:U.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:U,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:U.VAL,RBV=MEC:PCI:HEX:BL:Upr:rbv,DMOV=MEC:PCI:HEX:BL:U.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:U,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:U,ALIAS=MEC:PCI:BL:U:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:V,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:V.VAL,RBV=MEC:PCI:HEX:BL:Vpr:rbv,DMOV=MEC:PCI:HEX:BL:V.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:V,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:V.VAL,RBV=MEC:PCI:HEX:BL:Vpr:rbv,DMOV=MEC:PCI:HEX:BL:V.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:V,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:V.VAL,RBV=MEC:PCI:HEX:BL:Vpr:rbv,DMOV=MEC:PCI:HEX:BL:V.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:V,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:V.VAL,RBV=MEC:PCI:HEX:BL:Vpr:rbv,DMOV=MEC:PCI:HEX:BL:V.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:V,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:V.VAL,RBV=MEC:PCI:HEX:BL:Vpr:rbv,DMOV=MEC:PCI:HEX:BL:V.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:V,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:V,ALIAS=MEC:PCI:BL:V:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:W,STATE=Alignment_Pin,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:W.VAL,RBV=MEC:PCI:HEX:BL:Wpr:rbv,DMOV=MEC:PCI:HEX:BL:W.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:W,STATE=Set_1,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:W.VAL,RBV=MEC:PCI:HEX:BL:Wpr:rbv,DMOV=MEC:PCI:HEX:BL:W.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:W,STATE=Set_2,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:W.VAL,RBV=MEC:PCI:HEX:BL:Wpr:rbv,DMOV=MEC:PCI:HEX:BL:W.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:W,STATE=Set_3,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:W.VAL,RBV=MEC:PCI:HEX:BL:Wpr:rbv,DMOV=MEC:PCI:HEX:BL:W.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:BL:W,STATE=Set_4,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:BL:W.VAL,RBV=MEC:PCI:HEX:BL:Wpr:rbv,DMOV=MEC:PCI:HEX:BL:W.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL:W,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:BL:W,ALIAS=MEC:PCI:BL:W:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:XC,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:X.VAL,RBV=MEC:PCI:MMS:TC:X.RBV,DMOV=MEC:PCI:MMS:TC:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:XC,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:X.VAL,RBV=MEC:PCI:MMS:TC:X.RBV,DMOV=MEC:PCI:MMS:TC:X.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:XC,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:X.VAL,RBV=MEC:PCI:MMS:TC:X.RBV,DMOV=MEC:PCI:MMS:TC:X.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TC:XC,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:TC:X,ALIAS=MEC:PCI:TC:XC:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:ZC,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:Z.VAL,RBV=MEC:PCI:MMS:TC:Z.RBV,DMOV=MEC:PCI:MMS:TC:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:ZC,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:Z.VAL,RBV=MEC:PCI:MMS:TC:Z.RBV,DMOV=MEC:PCI:MMS:TC:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:ZC,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TC:Z.VAL,RBV=MEC:PCI:MMS:TC:Z.RBV,DMOV=MEC:PCI:MMS:TC:Z.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TC:ZC,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:TC:Z,ALIAS=MEC:PCI:TC:ZC:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:S,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TG:S.VAL,RBV=MEC:PCI:MMS:TG:S.RBV,DMOV=MEC:PCI:MMS:TG:S.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:S,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TG:S.VAL,RBV=MEC:PCI:MMS:TG:S.RBV,DMOV=MEC:PCI:MMS:TG:S.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TC:S,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:MMS:TG:S.VAL,RBV=MEC:PCI:MMS:TG:S.RBV,DMOV=MEC:PCI:MMS:TG:S.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TC:S,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:MMS:TG:S,ALIAS=MEC:PCI:TC:S:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:XF,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Xpr.VAL,RBV=MEC:PCI:HEX:TG:Xpr:rbv,DMOV=MEC:PCI:HEX:TG:Xpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:XF,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Xpr.VAL,RBV=MEC:PCI:HEX:TG:Xpr:rbv,DMOV=MEC:PCI:HEX:TG:Xpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:XF,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Xpr.VAL,RBV=MEC:PCI:HEX:TG:Xpr:rbv,DMOV=MEC:PCI:HEX:TG:Xpr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:XF,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Xpr,ALIAS=MEC:PCI:TG:XF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:YF,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Ypr.VAL,RBV=MEC:PCI:HEX:TG:Ypr:rbv,DMOV=MEC:PCI:HEX:TG:Ypr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:YF,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Ypr.VAL,RBV=MEC:PCI:HEX:TG:Ypr:rbv,DMOV=MEC:PCI:HEX:TG:Ypr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:YF,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Ypr.VAL,RBV=MEC:PCI:HEX:TG:Ypr:rbv,DMOV=MEC:PCI:HEX:TG:Ypr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:YF,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Ypr,ALIAS=MEC:PCI:TG:YF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:ZF,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Zpr.VAL,RBV=MEC:PCI:HEX:TG:Zpr:rbv,DMOV=MEC:PCI:HEX:TG:Zpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:ZF,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Zpr.VAL,RBV=MEC:PCI:HEX:TG:Zpr:rbv,DMOV=MEC:PCI:HEX:TG:Zpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:ZF,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Zpr.VAL,RBV=MEC:PCI:HEX:TG:Zpr:rbv,DMOV=MEC:PCI:HEX:TG:Zpr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:ZF,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Zpr,ALIAS=MEC:PCI:TG:ZF:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:U,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Upr.VAL,RBV=MEC:PCI:HEX:TG:Upr:rbv,DMOV=MEC:PCI:HEX:TG:Upr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:U,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Upr.VAL,RBV=MEC:PCI:HEX:TG:Upr:rbv,DMOV=MEC:PCI:HEX:TG:Upr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:U,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Upr.VAL,RBV=MEC:PCI:HEX:TG:Upr:rbv,DMOV=MEC:PCI:HEX:TG:Upr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:U,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Upr,ALIAS=MEC:PCI:TG:U:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:V,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Vpr.VAL,RBV=MEC:PCI:HEX:TG:Vpr:rbv,DMOV=MEC:PCI:HEX:TG:Vpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:V,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Vpr.VAL,RBV=MEC:PCI:HEX:TG:Vpr:rbv,DMOV=MEC:PCI:HEX:TG:Vpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:V,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Vpr.VAL,RBV=MEC:PCI:HEX:TG:Vpr:rbv,DMOV=MEC:PCI:HEX:TG:Vpr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:V,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Vpr,ALIAS=MEC:PCI:TG:V:MOTOR" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:W,STATE=Standby,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Wpr.VAL,RBV=MEC:PCI:HEX:TG:Wpr:rbv,DMOV=MEC:PCI:HEX:TG:Wpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:W,STATE=PCI,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Wpr.VAL,RBV=MEC:PCI:HEX:TG:Wpr:rbv,DMOV=MEC:PCI:HEX:TG:Wpr.DMOV" )
dbLoadRecords( "$(TOP)/db/one_state.db", "DEVICE=MEC:PCI:TG:W,STATE=PTY,SET=0.5,DELTA=0.5,MOVER=MEC:PCI:HEX:TG:Wpr.VAL,RBV=MEC:PCI:HEX:TG:Wpr:rbv,DMOV=MEC:PCI:HEX:TG:Wpr.DMOV" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:TG:W,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=MEC:PCI:HEX:TG:Wpr,ALIAS=MEC:PCI:TG:W:MOTOR" )

dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:BL,STATE=Alignment_Pin,COMP1=MEC:PCI:BL:XC,COMP2=MEC:PCI:BL:ZC,COMP3=MEC:PCI:BL:XF,COMP4=MEC:PCI:BL:YF,COMP5=MEC:PCI:BL:ZF,COMP6=MEC:PCI:BL:U,COMP7=MEC:PCI:BL:V,COMP8=MEC:PCI:BL:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:BL,STATE=Set_1,COMP1=MEC:PCI:BL:XC,COMP2=MEC:PCI:BL:ZC,COMP3=MEC:PCI:BL:XF,COMP4=MEC:PCI:BL:YF,COMP5=MEC:PCI:BL:ZF,COMP6=MEC:PCI:BL:U,COMP7=MEC:PCI:BL:V,COMP8=MEC:PCI:BL:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:BL,STATE=Set_2,COMP1=MEC:PCI:BL:XC,COMP2=MEC:PCI:BL:ZC,COMP3=MEC:PCI:BL:XF,COMP4=MEC:PCI:BL:YF,COMP5=MEC:PCI:BL:ZF,COMP6=MEC:PCI:BL:U,COMP7=MEC:PCI:BL:V,COMP8=MEC:PCI:BL:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:BL,STATE=Set_3,COMP1=MEC:PCI:BL:XC,COMP2=MEC:PCI:BL:ZC,COMP3=MEC:PCI:BL:XF,COMP4=MEC:PCI:BL:YF,COMP5=MEC:PCI:BL:ZF,COMP6=MEC:PCI:BL:U,COMP7=MEC:PCI:BL:V,COMP8=MEC:PCI:BL:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:BL,STATE=Set_4,COMP1=MEC:PCI:BL:XC,COMP2=MEC:PCI:BL:ZC,COMP3=MEC:PCI:BL:XF,COMP4=MEC:PCI:BL:YF,COMP5=MEC:PCI:BL:ZF,COMP6=MEC:PCI:BL:U,COMP7=MEC:PCI:BL:V,COMP8=MEC:PCI:BL:W" )
dbLoadRecords( "$(TOP)/db/device_with_5states.db", "DEVICE=MEC:PCI:BL,STATE1=Alignment_Pin,SEVR1=NO_ALARM,STATE2=Set_1,SEVR2=NO_ALARM,STATE3=Set_2,SEVR3=NO_ALARM,STATE4=Set_3,SEVR4=NO_ALARM,STATE5=Set_4,SEVR5=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=,ALIAS=MEC:PCI:BL:MOTOR" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:MODE,STATE=Standby,COMP1=MEC:PCI:TC:XC,COMP2=MEC:PCI:TC:ZC,COMP3=MEC:PCI:TG:XF,COMP4=MEC:PCI:TG:YF,COMP5=MEC:PCI:TG:ZF,COMP6=MEC:PCI:TG:U,COMP7=MEC:PCI:TG:V,COMP8=MEC:PCI:TG:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:MODE,STATE=PCI,COMP1=MEC:PCI:TC:XC,COMP2=MEC:PCI:TC:ZC,COMP3=MEC:PCI:TG:XF,COMP4=MEC:PCI:TG:YF,COMP5=MEC:PCI:TG:ZF,COMP6=MEC:PCI:TG:U,COMP7=MEC:PCI:TG:V,COMP8=MEC:PCI:TG:W" )
dbLoadRecords( "$(TOP)/db/state_with_8components.db", "DEVICE=MEC:PCI:MODE,STATE=PTY,COMP1=MEC:PCI:TC:XC,COMP2=MEC:PCI:TC:ZC,COMP3=MEC:PCI:TG:XF,COMP4=MEC:PCI:TG:YF,COMP5=MEC:PCI:TG:ZF,COMP6=MEC:PCI:TG:U,COMP7=MEC:PCI:TG:V,COMP8=MEC:PCI:TG:W" )
dbLoadRecords( "$(TOP)/db/device_with_3states.db", "DEVICE=MEC:PCI:MODE,STATE1=Standby,SEVR1=NO_ALARM,STATE2=PCI,SEVR2=NO_ALARM,STATE3=PTY,SEVR3=NO_ALARM" )
dbLoadRecords( "$(TOP)/db/alias.db", "SOURCE=,ALIAS=MEC:PCI:MODE:MOTOR" )


var imsRecordDebug 0
# var save_restoreDebug 30

# autosave
save_restoreSet_status_prefix( "$(EPICS_NAME):" )
save_restoreSet_NumSeqFiles       (  5 )
save_restoreSet_SeqPeriodInSeconds( 30 )

save_restoreSet_IncompleteSetsOk  (  1 )
save_restoreSet_DatedBackupFiles  (  1 )

set_requestfile_path ( "$(PWD)/../../autosave"          )
set_savefile_path    ( "$(IOC_DATA)/ioc-mec-pci-ims/autosave" )

set_pass0_restoreFile( "ioc-mec-pci-ims.sav"                  )
set_pass1_restoreFile( "ioc-mec-pci-ims.sav"                  )

# Initialize the IOC and start processing records
iocInit()

create_monitor_set( "ioc-mec-pci-ims.req", 30, "" );

# All IOCs should dump some common info after initial startup.
< /reg/d/iocCommon/All/post_linux.cmd

