#!/reg/g/pcds/epics/ioc/common/pvNotepad/R2.1.0/bin/rhel7-x86_64/pvNotepad

epicsEnvSet( "EPICS_NAME", "IOC:XPP:USERPV" )
epicsEnvSet( "ENGINEER",  "Reece Fiebich (rfiebich)" )
epicsEnvSet( "LOCATION",  "SLAC:LCLS:XPP" )
epicsEnvSet( "IOCSH_PS1", "ioc-xpp-userPV> ")
epicsEnvSet( "IOCTOP",       "/reg/g/pcds/epics/ioc/common/pvNotepad/R2.1.0" )
epicsEnvSet( "BUILD_TOP",    "/reg/g/pcds/epics/ioc/xpp/pvNotepad/R1.1.9/build" )
epicsEnvSet( "EPICS_PVA_AUTO_ADDR_LIST",         "TRUE" )
epicsEnvSet( "EPICS_PVAS_AUTO_BEACON_ADDR_LIST", "TRUE" )

< envPaths

# Run common startup commands for linux soft IOC's
< /reg/d/iocCommon/All/pre_linux.cmd

# Register all support components
dbLoadDatabase("$(TOP)/dbd/pvNotepad.dbd")
pvNotepad_registerRecordDeviceDriver(pdbbase)

# Load record instances
dbLoadRecords("$(TOP)/db/iocSoft.db",            "IOC=$(EPICS_NAME)" )
dbLoadRecords("$(TOP)/db/save_restoreStatus.db", "P=$(EPICS_NAME):" )

#Standard array option

dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARI1,NELM=10,FTYPE=LONG")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARI2,NELM=10,FTYPE=LONG")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARF1,NELM=10,FTYPE=FLOAT")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARF2,NELM=10,FTYPE=FLOAT")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARS1,NELM=10,FTYPE=STRING")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:ARS2,NELM=10,FTYPE=STRING")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:F1")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:F2")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:F3")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:DAQ:CPV:NUM_VAL:01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:DAQ:CPV:NUM_VAL:02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:DAQ:CPV:NUM_VAL:03")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:DAQ:NEVT")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:DAQ:RUNNO")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:BEGIN,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:END,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:WAIT,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:DCONNECT,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:CONNECT,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:CONF,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:EXP,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:DAQ:COLLDONE,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_DESC:01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_DESC:02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_DESC:03,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_VAL:01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_VAL:02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:STR_VAL:03,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:NUM_DESC:01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:NUM_DESC:02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:DAQ:CPV:NUM_DESC:03,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:SCAN:NSHOTS")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:SCAN:NSTEPS")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:SCAN:ISTEP")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:SCAN:ISSCAN,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:SCAN:SCANVAR00,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:SCAN:SCANVAR01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:SCAN:SCANVAR02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MIN00")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MIN01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MIN02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MAX00")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MAX01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:SCAN:MAX02")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:01")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:02")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:03")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:04")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:05")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:06")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:07")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:08")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:09")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:VARS:INT:10")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:01,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:02,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:03,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:04,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:05,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:06,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:07,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:08,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:09,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_bo.db",     "PV=XPP:VARS:BIN:10,ZNAM=False,ONAM=True,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:01,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:02,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:03,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:04,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:05,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:06,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:07,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:08,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:09,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_stringin.db",     "PV=XPP:VARS:STRING:10,DTYP=Soft Channel")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:01")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:02")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:03")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:04")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:05")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:06")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:07")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:08")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:09")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:VARS:FLOAT:10")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:TEMP0,PREC=4,DESC=R39:140K Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:TEMP1,PREC=4,DESC=R39:140K Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:TEMP2,PREC=4,DESC=R39:140K Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:TEMP3,PREC=4,DESC=R39:140K Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:04:TEMP0,PREC=4,DESC=R39:140K:04 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:04:TEMP1,PREC=4,DESC=R39:140K:04 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:04:TEMP2,PREC=4,DESC=R39:140K:04 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:04:TEMP3,PREC=4,DESC=R39:140K:04 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:06:TEMP0,PREC=4,DESC=R39:140K:06 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:06:TEMP1,PREC=4,DESC=R39:140K:06 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:06:TEMP2,PREC=4,DESC=R39:140K:06 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:06:TEMP3,PREC=4,DESC=R39:140K:06 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:07:TEMP0,PREC=4,DESC=R39:140K:07 Temperature 0,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:07:TEMP1,PREC=4,DESC=R39:140K:07 Temperature 1,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:07:TEMP2,PREC=4,DESC=R39:140K:07 Temperature 2,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:R39:140K:07:TEMP3,PREC=4,DESC=R39:140K:07 Temperature 3,SCAN=Passive,MDEL=-1.,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:SET1,PREC=16,DESC=MCC Photon Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:SET2,PREC=16,DESC=MCC Photon Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:REF1,PREC=16,DESC=MCC Photon Energy Reference,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:REF2,PREC=16,DESC=MCC Photon Energy Reference,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:VER,PREC=16,DESC=MCC Photon Energy PV Vernier,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:UND,PREC=16,DESC=MCC Photon Energy PV Undulator,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:MCC:EPHOT:REQ,PREC=16,DESC=MCC Photon Energy PV Request,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:CCM:E,PREC=16,DESC=CCM Energy,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:CCM:Theta0,PREC=16,DESC=CCM Theta0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:FS3:T0_SHIFTER,PREC=16,DESC=XPP Laser FS3 T0_SHIFTER,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:LeCroyScope_P1,PREC=16,DESC=XPP Laser Lecroy Scope MONITOR for P1,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:LeCroyScope_P2,PREC=16,DESC=XPP Laser Lecroy Scope MONITOR for P2,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:LeCroyScope_P3,PREC=16,DESC=XPP Laser Lecroy Scope MONITOR for P3,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:LeCroyScope_P4,PREC=16,DESC=XPP Laser Lecroy Scope MONITOR for P4,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E_PULSE,PREC=16,DESC=XPP Laser E_PULSE,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E0,PREC=16,DESC=XPP Laser E0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E_LEAK,PREC=16,DESC=XPP Laser E_LEAK,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TIME_DELAY,PREC=16,DESC=XPP Laser Time Delay,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:FS3_MIN,PREC=16,DESC=XPP Laser FS3 Min,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:FS3_MAX,PREC=16,DESC=XPP Laser FS3 MAX,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:EVR0_OSC,PREC=16,DESC=XPP Laser EVR0_Osc.,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:EVR0_GATE,PREC=16,DESC=XPP Laser EVR0 Gate,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:SDG0,PREC=16,DESC=XPP Laser SDG0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E_PULSE2,PREC=16,DESC=XPP Laser 2 E_Pulse,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E02,PREC=16,DESC=XPP Laser 2 E0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:E_LEAK2,PREC=16,DESC=XPP Laser 2 E_LEAK,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:VIT:T0,PREC=16,DESC=XPP Laser Vitara T0,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:VIT:TD,PREC=16,DESC=XPP Laser Vitara TD,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LXT,PREC=16,DESC=XPP LXT,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LXTTC,PREC=16,DESC=XPP LXTTC,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:CP_WP_POS,PREC=16,DESC=XPP Laser CP Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:CP_WP_OFF,PREC=16,DESC=XPP Laser CP Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OUT_WP_POS,PREC=16,DESC=XPP Laser OUT Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OUT_WP_OFF,PREC=16,DESC=XPP Laser OUT Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:CP_TRA_POS,PREC=16,DESC=XPP Laser CP Trans Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:CP_TRA_OFF,PREC=16,DESC=XPP Laser CP Trans OFF,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_H_POS,PREC=16,DESC=XPP Laser L1 Horizontal Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_H_OFF,PREC=16,DESC=XPP Laser L1 Horizontal Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_V_POS,PREC=16,DESC=XPP Laser L1 Vertical Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_V_OFF,PREC=16,DESC=XPP Laser L1 Vertical Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_F_POS,PREC=16,DESC=XPP Laser L1 Focus Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:L1_F_OFF,PREC=16,DESC=XPP Laser L1 Focus Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:NEW_7_POS,PREC=16,DESC=XPP Laser Newport 7 Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:NEW_7_OFF,PREC=16,DESC=XPP Laser Newport 7 Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OPA_WP_POS,PREC=16,DESC=XPP Laser OPA Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OPA_WP_OFF,PREC=16,DESC=XPP Laser OPA Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OPA_COMP_POS,PREC=16,DESC=XPP Laser OPA Compressor Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:OPA_COMP_OFF,PREC=16,DESC=XPP Laser OPA Compressor Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_WP_POS,PREC=16,DESC=XPP Laser TT Waveplate Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_WP_OFF,PREC=16,DESC=XPP Laser TT Waveplate Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_COMP_POS,PREC=16,DESC=XPP Laser TT Compressor Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_COMP_OFF,PREC=16,DESC=XPP Laser TT Compressor Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSH_POS,PREC=16,DESC=XPP Laser TT Lens Horiz. Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSH_OFF,PREC=16,DESC=XPP Laser TT Lens Horiz. Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSV_POS,PREC=16,DESC=XPP Laser TT Lens Vert. Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSV_OFF,PREC=16,DESC=XPP Laser TT Lens Vert. Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSF_POS,PREC=16,DESC=XPP Laser TT Lens Focus Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_LENSF_OFF,PREC=16,DESC=XPP Laser TT Lens Focus Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_DELAY_POS,PREC=16,DESC=XPP Laser tt_delay Pos,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:USER:LAS:TT_DELAY_OFF,PREC=16,DESC=XPP Laser tt_delay Off,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:TIMETOOL:TTALL,NELM=8,NORD=8,FTYPE=DOUBLE,EGU=Counts,PREC=16,DESC=XPP TT PeakPos Ampl Vector,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:TIMETOOL:TTALL2,NELM=8,NORD=8,FTYPE=DOUBLE,EGU=Counts,PREC=16,DESC=XPP TT PeakPos Ampl Vector,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_waveform.db",     "PV=XPP:USER:ENCODER,NELM=3,NORD=3,FTYPE=DOUBLE,EGU=Counts,PREC=0,DESC=Encoder Counts,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_mbbo.db",     "PV=XPP:ISTAR:GateMode,DESC=iStar GateMode,ZRST=CWOff,ZRVL=0,ONST=CWOn,ONVL=1,TWST=FireAndGate,TWVL=2")
dbLoadRecords("$(TOP)/db/special_longout.db",     "PV=XPP:ISTAR:MCPGain,DESC=iStar MCPGain")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:CCM:THETA0,PREC=16,DESC=CCM Calc theta0 constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:CCM:DSPACING,PREC=16,DESC=CCM Calc dspacing constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:CCM:GR,PREC=16,DESC=CCM Calc gr constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")
dbLoadRecords("$(TOP)/db/special_ao.db",     "PV=XPP:CCM:GD,PREC=16,DESC=CCM Calc gd constant,DTYP=Soft Channel,SCAN=Passive,PINI=YES")

# Setup autosave
save_restoreSet_status_prefix("$(EPICS_NAME):" )
save_restoreSet_IncompleteSetsOk( 1 )
save_restoreSet_DatedBackupFiles( 1 )

set_requestfile_path( "$(PWD)/../../autosave"             )
set_savefile_path   ( "$(IOC_DATA)/ioc-xpp-userPV/autosave" )

set_pass0_restoreFile( "ioc-xpp-userPV.sav" )        #just restore the settings
set_pass1_restoreFile( "ioc-xpp-userPV.sav" )        #just restore the settings


# Initialize the IOC and start processing records
iocInit()

# Start autosave backups
create_monitor_set( "ioc-xpp-userPV.req", 30, "" )

# All IOCs should dump some common info after initial startup.
< /reg/d/iocCommon/All/post_linux.cmd

